require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LinkcategoriesController do

  # This should return the minimal set of attributes required to create a valid
  # Linkcategory. As you add validations to Linkcategory, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LinkcategoriesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all linkcategories as @linkcategories" do
      linkcategory = Linkcategory.create! valid_attributes
      get :index, {}, valid_session
      assigns(:linkcategories).should eq([linkcategory])
    end
  end

  describe "GET show" do
    it "assigns the requested linkcategory as @linkcategory" do
      linkcategory = Linkcategory.create! valid_attributes
      get :show, {:id => linkcategory.to_param}, valid_session
      assigns(:linkcategory).should eq(linkcategory)
    end
  end

  describe "GET new" do
    it "assigns a new linkcategory as @linkcategory" do
      get :new, {}, valid_session
      assigns(:linkcategory).should be_a_new(Linkcategory)
    end
  end

  describe "GET edit" do
    it "assigns the requested linkcategory as @linkcategory" do
      linkcategory = Linkcategory.create! valid_attributes
      get :edit, {:id => linkcategory.to_param}, valid_session
      assigns(:linkcategory).should eq(linkcategory)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Linkcategory" do
        expect {
          post :create, {:linkcategory => valid_attributes}, valid_session
        }.to change(Linkcategory, :count).by(1)
      end

      it "assigns a newly created linkcategory as @linkcategory" do
        post :create, {:linkcategory => valid_attributes}, valid_session
        assigns(:linkcategory).should be_a(Linkcategory)
        assigns(:linkcategory).should be_persisted
      end

      it "redirects to the created linkcategory" do
        post :create, {:linkcategory => valid_attributes}, valid_session
        response.should redirect_to(Linkcategory.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved linkcategory as @linkcategory" do
        # Trigger the behavior that occurs when invalid params are submitted
        Linkcategory.any_instance.stub(:save).and_return(false)
        post :create, {:linkcategory => {}}, valid_session
        assigns(:linkcategory).should be_a_new(Linkcategory)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Linkcategory.any_instance.stub(:save).and_return(false)
        post :create, {:linkcategory => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested linkcategory" do
        linkcategory = Linkcategory.create! valid_attributes
        # Assuming there are no other linkcategories in the database, this
        # specifies that the Linkcategory created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Linkcategory.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => linkcategory.to_param, :linkcategory => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested linkcategory as @linkcategory" do
        linkcategory = Linkcategory.create! valid_attributes
        put :update, {:id => linkcategory.to_param, :linkcategory => valid_attributes}, valid_session
        assigns(:linkcategory).should eq(linkcategory)
      end

      it "redirects to the linkcategory" do
        linkcategory = Linkcategory.create! valid_attributes
        put :update, {:id => linkcategory.to_param, :linkcategory => valid_attributes}, valid_session
        response.should redirect_to(linkcategory)
      end
    end

    describe "with invalid params" do
      it "assigns the linkcategory as @linkcategory" do
        linkcategory = Linkcategory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Linkcategory.any_instance.stub(:save).and_return(false)
        put :update, {:id => linkcategory.to_param, :linkcategory => {}}, valid_session
        assigns(:linkcategory).should eq(linkcategory)
      end

      it "re-renders the 'edit' template" do
        linkcategory = Linkcategory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Linkcategory.any_instance.stub(:save).and_return(false)
        put :update, {:id => linkcategory.to_param, :linkcategory => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested linkcategory" do
      linkcategory = Linkcategory.create! valid_attributes
      expect {
        delete :destroy, {:id => linkcategory.to_param}, valid_session
      }.to change(Linkcategory, :count).by(-1)
    end

    it "redirects to the linkcategories list" do
      linkcategory = Linkcategory.create! valid_attributes
      delete :destroy, {:id => linkcategory.to_param}, valid_session
      response.should redirect_to(linkcategories_url)
    end
  end

end
