require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe VocsController do

  # This should return the minimal set of attributes required to create a valid
  # Voc. As you add validations to Voc, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { :german => "german", 
      :wylie => "wy li e",
      :source_id => 1,
      :grammar_id => 1,
      :category_id => 1,                                
      :info => "Some Info" }
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # VocsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all vocs as @vocs" do
      voc = Voc.create! valid_attributes
      get :index, {}, valid_session
      assigns(:vocs).should eq([voc])
    end
  end

  describe "GET show" do
    it "assigns the requested voc as @voc" do
      voc = Voc.create! valid_attributes
      get :show, {:id => voc.to_param}, valid_session
      assigns(:voc).should eq(voc)
    end
  end

  describe "GET new" do
    it "assigns a new voc as @voc" do
      get :new, {}, valid_session
      assigns(:voc).should be_a_new(Voc)
    end
  end

  describe "GET edit" do
    it "assigns the requested voc as @voc" do
      voc = Voc.create! valid_attributes
      get :edit, {:id => voc.to_param}, valid_session
      assigns(:voc).should eq(voc)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Voc" do
        expect {
          post :create, {:voc => valid_attributes}, valid_session
        }.to change(Voc, :count).by(1)
      end

      it "assigns a newly created voc as @voc" do
        post :create, {:voc => valid_attributes}, valid_session
        assigns(:voc).should be_a(Voc)
        assigns(:voc).should be_persisted
      end

      it "redirects to the created voc" do
        post :create, {:voc => valid_attributes}, valid_session
        response.should redirect_to(Voc.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved voc as @voc" do
        # Trigger the behavior that occurs when invalid params are submitted
        Voc.any_instance.stub(:save).and_return(false)
        post :create, {:voc => {}}, valid_session
        assigns(:voc).should be_a_new(Voc)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Voc.any_instance.stub(:save).and_return(false)
        post :create, {:voc => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested voc" do
        voc = Voc.create! valid_attributes
        # Assuming there are no other vocs in the database, this
        # specifies that the Voc created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Voc.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => voc.to_param, :voc => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested voc as @voc" do
        voc = Voc.create! valid_attributes
        put :update, {:id => voc.to_param, :voc => valid_attributes}, valid_session
        assigns(:voc).should eq(voc)
      end

      it "redirects to the voc" do
        voc = Voc.create! valid_attributes
        put :update, {:id => voc.to_param, :voc => valid_attributes}, valid_session
        response.should redirect_to(voc)
      end
    end

    describe "with invalid params" do
      it "assigns the voc as @voc" do
        voc = Voc.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Voc.any_instance.stub(:save).and_return(false)
        put :update, {:id => voc.to_param, :voc => {}}, valid_session
        assigns(:voc).should eq(voc)
      end

      it "re-renders the 'edit' template" do
        voc = Voc.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Voc.any_instance.stub(:save).and_return(false)
        put :update, {:id => voc.to_param, :voc => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested voc" do
      voc = Voc.create! valid_attributes
      expect {
        delete :destroy, {:id => voc.to_param}, valid_session
      }.to change(Voc, :count).by(-1)
    end

    it "redirects to the vocs list" do
      voc = Voc.create! valid_attributes
      delete :destroy, {:id => voc.to_param}, valid_session
      response.should redirect_to(vocs_url)
    end
  end

end
